
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/membersite?serverTimezone=JST
    username: root
    password: mysql

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    org:
      springframework: WARN
    '[com.example.membersite.model.mapper]': DEBUG